// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace VSC.FeatureFiles_TCs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("User can see Promotion details in cart.")]
    public partial class UserCanSeePromotionDetailsInCart_Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "VerifyCartElements.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "User can see Promotion details in cart.", "    In order to be informed what I am shopping for\r\n    As a new user\r\n    I want" +
                    " to see relevant Promotion details in Cart depending on my selection.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BOX za 1 EUR - No Subscription")]
        public virtual void BOXZa1EUR_NoSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOX za 1 EUR - No Subscription", null, ((string[])(null)));
#line 7
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
        testRunner.When("I select \"BOX za 1 EUR\" Promotion", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
        testRunner.Then("in Cart I see \"contract lenght\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BOX za 1 EUR - Subscription 3 months")]
        public virtual void BOXZa1EUR_Subscription3Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOX za 1 EUR - Subscription 3 months", null, ((string[])(null)));
#line 12
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 13
        testRunner.When("I select Promotion \"BOX za 1 EUR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
        testRunner.And("I select Subscription \"3 meseca\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\", \"device price\", \"device price discount\", \"device activa" +
                    "tion fee\", \"device transportation fee\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BOX za 1 EUR - Subscription 6 months")]
        public virtual void BOXZa1EUR_Subscription6Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOX za 1 EUR - Subscription 6 months", null, ((string[])(null)));
#line 18
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 19
        testRunner.When("I select Promotion \"BOX za 1 EUR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
        testRunner.And("I select Subscription \"6 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\", \"device price\", \"device price discount\", \"device activa" +
                    "tion fee\", \"device transportation fee\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BOX za 1 EUR - Subscription 12 months")]
        public virtual void BOXZa1EUR_Subscription12Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOX za 1 EUR - Subscription 12 months", null, ((string[])(null)));
#line 24
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 25
        testRunner.When("I select Promotion \"BOX za 1 EUR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
        testRunner.And("I select Subscription \"12 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\", \"device price\", \"device price discount\", \"device activa" +
                    "tion fee\", \"device transportation fee\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("50% popusta na box - Predefined Subscription")]
        public virtual void _50PopustaNaBox_PredefinedSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("50% popusta na box - Predefined Subscription", null, ((string[])(null)));
#line 30
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 31
        testRunner.When("I select Promotion \"50% popusta na box\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\", \"device price\", \"device price discount\", \"device activa" +
                    "tion fee\", \"device transportation fee\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BOX bez akcijske cene - No Subscription")]
        public virtual void BOXBezAkcijskeCene_NoSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOX bez akcijske cene - No Subscription", null, ((string[])(null)));
#line 35
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 36
        testRunner.When("I select Promotion \"BOX bez akcijske cene\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\", \"device price\", \"device price discount\", \"device activa" +
                    "tion fee\", \"device transportation fee\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BOX bez akcijske cene - Subscription 3 months")]
        public virtual void BOXBezAkcijskeCene_Subscription3Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOX bez akcijske cene - Subscription 3 months", null, ((string[])(null)));
#line 40
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 41
        testRunner.When("I select Promotion \"BOX bez akcijske cene\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
        testRunner.And("I select Subscription \"3 meseca\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\", \"device price\", \"device price discount\", \"device activa" +
                    "tion fee\", \"device transportation fee\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BOX bez akcijske cene - Subscription 6 months")]
        public virtual void BOXBezAkcijskeCene_Subscription6Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOX bez akcijske cene - Subscription 6 months", null, ((string[])(null)));
#line 46
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 47
        testRunner.When("I select Promotion \"BOX bez akcijske cene\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
        testRunner.And("I select Subscription \"6 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\", \"device price\", \"device price discount\", \"device activa" +
                    "tion fee\", \"device transportation fee\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("BOX bez akcijske cene - Subscription 12 months")]
        public virtual void BOXBezAkcijskeCene_Subscription12Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("BOX bez akcijske cene - Subscription 12 months", null, ((string[])(null)));
#line 52
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 53
        testRunner.When("I select Promotion \"BOX bez akcijske cene\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
        testRunner.And("I select Subscription \"12 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\", \"device price\", \"device price discount\", \"device activa" +
                    "tion fee\", \"device transportation fee\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 meseca gratis - No Subscription")]
        public virtual void _3MesecaGratis_NoSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 meseca gratis - No Subscription", null, ((string[])(null)));
#line 57
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 58
        testRunner.When("I select \"3 meseca gratis\" Promotion", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
        testRunner.Then("in Cart I see \"contract lenght\".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 meseca gratis - Subscription 3 months")]
        public virtual void _3MesecaGratis_Subscription3Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 meseca gratis - Subscription 3 months", null, ((string[])(null)));
#line 61
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 62
        testRunner.When("I select Promotion \"3 meseca gratis\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
        testRunner.And("I select Subscription \"3 meseca\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 meseca gratis - Subscription 6 months")]
        public virtual void _3MesecaGratis_Subscription6Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 meseca gratis - Subscription 6 months", null, ((string[])(null)));
#line 68
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 69
        testRunner.When("I select Promotion \"3 meseca gratis\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
        testRunner.And("I select Subscription \"6 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 meseca gratis - Subscription 12 months")]
        public virtual void _3MesecaGratis_Subscription12Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 meseca gratis - Subscription 12 months", null, ((string[])(null)));
#line 74
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 75
        testRunner.When("I select Promotion \"3 meseca gratis\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
        testRunner.And("I select Subscription \"12 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Plati 10 gledaj 12 meseci - Predefined Subscription")]
        public virtual void Plati10Gledaj12Meseci_PredefinedSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Plati 10 gledaj 12 meseci - Predefined Subscription", null, ((string[])(null)));
#line 80
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 81
        testRunner.When("I select Promotion \"Plati 10 gledaj 12 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Izaberi period trajanja pretplate - No Subscription")]
        public virtual void IzaberiPeriodTrajanjaPretplate_NoSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Izaberi period trajanja pretplate - No Subscription", null, ((string[])(null)));
#line 85
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 86
        testRunner.When("I select Promotion \"Izaberi period trajanja pretplate\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Izaberi period trajanja pretplate - Subscription 3 months")]
        public virtual void IzaberiPeriodTrajanjaPretplate_Subscription3Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Izaberi period trajanja pretplate - Subscription 3 months", null, ((string[])(null)));
#line 90
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 91
        testRunner.When("I select Promotion \"Izaberi period trajanja pretplate\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 92
        testRunner.And("I select Subscription \"3 meseca\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Izaberi period trajanja pretplate - Subscription 6 months")]
        public virtual void IzaberiPeriodTrajanjaPretplate_Subscription6Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Izaberi period trajanja pretplate - Subscription 6 months", null, ((string[])(null)));
#line 95
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 96
        testRunner.When("I select Promotion \"Izaberi period trajanja pretplate\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
        testRunner.And("I select Subscription \"6 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Izaberi period trajanja pretplate - Subscription 12 months")]
        public virtual void IzaberiPeriodTrajanjaPretplate_Subscription12Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Izaberi period trajanja pretplate - Subscription 12 months", null, ((string[])(null)));
#line 100
    this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 101
        testRunner.When("I select Promotion \"Izaberi period trajanja pretplate\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 102
        testRunner.And("I select Subscription \"12 meseci\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
        testRunner.Then("in Cart I see \"contract lenght\", \"subscription lenght\", \"subscription amount\", \"t" +
                    "otal amount\", \"savings\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
